@echo off
echo Starting Cherry Game...
echo.
echo Starting Backend Server...
start "Backend Server" cmd /k "cd backend && npm start"
echo.
echo Starting Frontend...
start "Frontend" cmd /k "cd frontend && npm start"
echo.
echo Both services are starting...
echo Backend will be available at: http://localhost:4000
echo Frontend will be available at: http://localhost:3000
echo.
echo Press any key to exit this window...
pause >nul
